name: CatholicMOTD
main: com.zachhof.catholicmotd.Messager
version: 1.3
api-version: 1.17
author: Graywolf212
commands:
  catholic:
    description: See the Catholic message-of-the-day!
    usage: /<command>
    aliases: motd
  calendar:
    description: Displays liturgial calendar info
    usage: /<command>
  verse:
    description: Displays verse of the day
    usage: /<command>
  catechism:
    description: Displays daily catechism passage
    usage: /<command>
  # quiz:
  #   description: Take a quiz on a previous daily verse or a random verse
  #   usage: /<command> (daily|random)